[[plugins]]
 repo = 'Shougo/dein.vim'

 [[plugins]]
 repo = 'Shougo/vimproc.vim'

 [[plugins]]
 repo = 'thinca/vim-quickrun'

 [[plugins]]
 repo = 'yuratomo/w3m.vim'

 [[plugins]]
 repo = 'kana/vim-smartinput'
